{{- if not .Values.secrets.existingSecret }}
{{- if or .Values.secrets.serverPassword .Values.rcon.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vintage-story.fullname" . }}
  labels:
    {{- include "vintage-story.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.serverPassword }}
  {{ .Values.secrets.keys.serverPassword }}: {{ .Values.secrets.serverPassword | quote }}
  {{- end }}
  {{- if .Values.rcon.enabled }}
  {{- if not .Values.secrets.rconPassword }}
  {{- fail "secrets.rconPassword is required when rcon.enabled is true and secrets.existingSecret is empty" }}
  {{- end }}
  {{- if not .Values.secrets.rconWebSecretKey }}
  {{- fail "secrets.rconWebSecretKey is required when rcon.enabled is true and secrets.existingSecret is empty" }}
  {{- end }}
  {{- if not .Values.secrets.rconWebPassword }}
  {{- fail "secrets.rconWebPassword is required when rcon.enabled is true and secrets.existingSecret is empty" }}
  {{- end }}
  {{ .Values.secrets.keys.rconPassword }}: {{ .Values.secrets.rconPassword | quote }}
  {{ .Values.secrets.keys.rconWebSecretKey }}: {{ .Values.secrets.rconWebSecretKey | quote }}
  {{ .Values.secrets.keys.rconWebPassword }}: {{ .Values.secrets.rconWebPassword | quote }}
  {{- end }}
{{- end }}
{{- end }}

